spring:
  application:
    name: spring-ai-java-development
  ai:
    openai:
      api-key: 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
      embedding:
          options:
           model: text-embedding-ada-002
    vectorstore:
      redis:
        index-name: product-index
        prefix: product
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  ## This config is for Radis Vector database.
  data:
    redis:
      host: localhost
      port: 6379
  ## This config is for maximum audio file size for AI Transcription.
  servlet:
    multipart:
      max-file-size: 10MB

  ## This config is only with PG Vector Database.
#    vectorstore:
#      pgvector:
#        max-document-batch-size: 10000
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#        dimensions: 1536
#        schema-validation: false

  ## This config is only with PG Vector Database.
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver

  ## This config is only with PG Vector Database.
#  sql:
#    init:
#      schema-locations: classpath:init/schema.sql
#      mode: always



  ## This config is only with Ollama Model.
#  ai:
#    ollama:
#      chat:
#        model: mistral:latest
#    model:
#      chat: ollama
