spring:
  application:
    name: spring-ai-java-development
  ai:
    openai:
      api-key:
        embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      pgvector:
        max-document-batch-size: 10000
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres




#  ai:
#    ollama:
#      chat:
#        model: mistral:latest
#    model:
#      chat: ollama
